name: dismissible_toast
description:  A Flutter Dismissible Toast plugin.
version: 0.0.2
homepage: https://github.com/cr0manty/dismissible_toast.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


flutter:

